//******** FUNDRAISERS *******/
export const CREATE_FUNDRAISER = "CREATE_FUNDRAISER";
export const UPDATE_FUNDRAISER = "UPDATE_FUNDRAISER";
export const LOAD_FUNDRAISERS = "LOAD_FUNDRAISERS";
export const SAVING_FUNDRAISER = "SAVING_FUNDRAISER";
