//******** FUNDRAISERS *******/
export const SAVE_FUNDRAISER = "SAVE_FUNDRAISER";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const LOAD_FUNDRAISERS = "LOAD_FUNDRAISERS";
export const LOAD_FUNDRAISER_SUCCESS = "LOAD_FUNDRAISERS_SUCCESS";
export const UPDATE_DONATIONS_INFO = "UPDATE_DONATIONS_INFO";
export const UPDATE_BENEFICIARY = "UPDATE_BENEFICIARY";
